spring:
  datasource:
    url: jdbc:postgresql://10.22.49.150:5432/teste
    username: postgres
    password: password

  liquibase:
      enabled: true
      drop-first: false
      change-log: classpath:db/changelog/db.changelog-master.xml
      default-schema: public
